### ISSUE TITLE
set up todo graphql schema and resolver

### ISSUE THREAD

**Issue by Junjpan** [Junjpan/Recruiting-App-GraphQL-React-Redux#21]
resolver included the below functions:

- [x] add todo list, (date, details, status, priority etc)

- [x] Delete todo list

- [x] Edit todo list
